config/routes.rb
Rails.application.routes.draw do
  resources :animals do
    resources :sightings
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :sightings
  validates :name, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :animal
  validates :date, :presence => true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
    render :index
  end

  def show
    @animal = Animal.find(params[:id])
    render :show
  end

  def new
    @animal = Animal.new
    render :new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to animals_path
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    render :edit
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animals_path
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end

  private
  def animal_params
    params.require(:animal).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController

  def new
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new(sighting_params)
    if @sighting.save
      redirect_to animal_path(@sighting.animal)
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    render :edit
  end

  def update
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    if @sighting.update(sighting_params)
      redirect_to animal_path(@sighting.animal)
    else
      render :edit
    end
  end

  def destroy
    @sighting = Sighting.find(params[:id])
    @sighting.destroy
    redirect_to animal_path(@sighting.animal)
  end

private
  def sighting_params
    params.require(:sighting).permit(:date, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<%= render "layouts/errors", :object => @animal %>

<%= form_for @animal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/animals/edit.html.erb
<h1>Edit animal</h1>

<%= render "form" %>

app/views/animals/index.html.erb
<h1>Animals</h1>

<ul>
  <% @animals.each do |animal| %>
    <li><%= link_to animal.name, animal_path(animal) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New Animal", new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render "form" %>

app/views/animals/show.html.erb
<h1><%= @animal.name %></h1>

<% if @animal.sightings.any? %>
  <h4>Here are the sightings for this animal:</h4>

  <ul>
    <% @animal.sightings.each do |sighting| %>
    <li>
      <%= sighting.date %> |
      <%= sighting.latitude %> |
      <%= sighting.longitude %> |
      <%= link_to "Edit", edit_animal_sighting_path(@animal, sighting) %> |
      <%= link_to "Delete", animal_sighting_path(@animal, sighting),
                                  :data => {:confirm => "You sure?",
                                  :method => "delete"} %>
    </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no sightings yet!</p>
<% end %>

<p><%= link_to "Add a sighting", new_animal_sighting_path(@animal) %></p>
<p><%= link_to "Edit Animal", edit_animal_path(@animal) %></p>
<p><%= link_to "Delete Animal", animal_path(@animal),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<p><%= link_to "Return to animals", animals_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/_form.html.erb
<%= render('layouts/errors', :object => @sighting) %>

<%= form_for [@animal, @sighting] do |f| %>
  <%= f.label :date %>
  <%= f.text_field :date %>
  <%= f.label :latitude %>
  <%= f.text_field :latitude %>
  <%= f.label :longitude %>
  <%= f.text_field :longitude %>
  <p> <%= f.submit %> </p>
<% end %>

app/views/sightings/edit.html.erb
<h1>Edit sighting</h1>

<%= render "form" %>

app/views/sightings/new.html.erb
<h1>New sighting for <%= @animal.name %></h1>

<%= render 'form' %>